#!/usr/bin/env python3
"""Build the browser fallback used when index.html is opened via file://."""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCES = {
    "searchIndex": ROOT / "data" / "search-index.json",
    "matchingRules": ROOT / "data" / "matching-rules.json",
    "guideManifest": ROOT / "data" / "guide-manifest.json",
}
OUTPUT = ROOT / "data" / "runtime-data.js"


def build_payload():
    return {name: json.loads(path.read_text(encoding="utf-8")) for name, path in SOURCES.items()}


def render_bundle(payload):
    return "// Generated by scripts/build_runtime_bundle.py; do not edit by hand.\nwindow.KRUG_GUIDE_DATA = " + json.dumps(payload, ensure_ascii=False, separators=(",", ":")) + ";\n"


def main():
    OUTPUT.write_text(render_bundle(build_payload()), encoding="utf-8")
    print(f"Wrote offline browser data to {OUTPUT}")


if __name__ == "__main__":
    main()
